// Agentic Workflow Templates for GenAI Control Center
// These workflows can be deployed to Dynatrace AutomationEngine

// Note: @dynatrace-sdk/client-automation is required for programmatic deployment
// For now, workflows are deployed via the Workflows UI using JSON import

/**
 * Weekly FinOps Digest Workflow
 * - Runs every Monday at 9 AM UTC
 * - Queries GenAI costs from Grail
 * - Uses Davis Intelligence to analyze and summarize
 * - Sends email digest to configured recipients
 */
export const FINOPS_DIGEST_WORKFLOW = {
  title: "GCC: Weekly FinOps Digest",
  description: "Agentic workflow that analyzes GenAI costs weekly and sends a summary digest via email. Uses Davis Intelligence for trend analysis and recommendations.",
  trigger: {
    schedule: {
      rule: "0 9 * * 1", // Every Monday at 9 AM
      timezone: "UTC",
      isActive: true
    }
  },
  schemaVersion: 3,
  tasks: {
    query_weekly_costs: {
      name: "query_weekly_costs",
      description: "Query GenAI token costs from last 7 days",
      action: "dynatrace.automations:execute-dql-query",
      input: {
        query: `fetch spans, from: now()-7d, to: now()
| filter isNotNull(gen_ai.provider.name) OR isNotNull(gen_ai.request.model)
| summarize {
    total_requests = count(),
    total_input_tokens = sum(coalesce(gen_ai.usage.prompt_tokens, gen_ai.usage.input_tokens, 0)),
    total_output_tokens = sum(coalesce(gen_ai.usage.completion_tokens, gen_ai.usage.output_tokens, 0)),
    avg_latency_ms = avg(duration / 1000000),
    error_count = countIf(otel.status_code == "ERROR")
  }, by: { provider = gen_ai.provider.name, model = gen_ai.request.model }
| sort total_requests desc`
      },
      position: { x: 0, y: 1 }
    },
    query_daily_trend: {
      name: "query_daily_trend", 
      description: "Query daily cost trend for week-over-week comparison",
      action: "dynatrace.automations:execute-dql-query",
      input: {
        query: `fetch spans, from: now()-14d, to: now()
| filter isNotNull(gen_ai.provider.name) OR isNotNull(gen_ai.request.model)
| summarize {
    requests = count(),
    tokens = sum(coalesce(gen_ai.usage.prompt_tokens, gen_ai.usage.input_tokens, 0) + coalesce(gen_ai.usage.completion_tokens, gen_ai.usage.output_tokens, 0))
  }, by: { day = bin(start_time, 1d) }
| sort day asc`
      },
      position: { x: 0, y: 2 },
      predecessors: ["query_weekly_costs"]
    },
    analyze_with_davis: {
      name: "analyze_with_davis",
      description: "Use Davis Intelligence to analyze costs and generate insights",
      action: "dynatrace.automations:dynatrace-intelligence",
      input: {
        prompt: `You are a FinOps analyst. Analyze the following GenAI usage data and provide:

1. **Executive Summary**: One paragraph overview of GenAI spending this week
2. **Top Cost Drivers**: Which models/providers consumed most tokens
3. **Week-over-Week Trend**: Is usage increasing or decreasing? By how much?
4. **Anomalies**: Any unusual spikes or patterns
5. **Recommendations**: 2-3 actionable cost optimization suggestions

Format the response as a professional email digest suitable for a CFO or Platform Lead.

**Weekly Usage Data:**
{{ result("query_weekly_costs") }}

**Daily Trend (14 days):**
{{ result("query_daily_trend") }}`
      },
      position: { x: 0, y: 3 },
      predecessors: ["query_daily_trend"]
    },
    send_email_digest: {
      name: "send_email_digest",
      description: "Send the FinOps digest via email",
      action: "dynatrace.automations:send-email",
      input: {
        to: ["{{$.trigger.emailRecipients}}"],
        subject: "🤖 GenAI FinOps Weekly Digest - {{ now() | date('MMMM D, YYYY') }}",
        body: `{{ result("analyze_with_davis") }}

---
Generated by GenAI Control Center (GCC)
Powered by Dynatrace Davis Intelligence`
      },
      position: { x: 0, y: 4 },
      predecessors: ["analyze_with_davis"],
      conditions: {
        states: {
          analyze_with_davis: "SUCCESS"
        }
      }
    }
  },
  ownerType: "USER",
  isPrivate: false
};

/**
 * Token Budget Alert Workflow
 * - Triggers when token usage exceeds threshold
 * - Sends Slack notification
 */
export const TOKEN_BUDGET_ALERT_WORKFLOW = {
  title: "GCC: Token Budget Alert",
  description: "Alert when GenAI token usage exceeds configured budget threshold",
  trigger: {
    schedule: {
      rule: "0 * * * *", // Every hour
      timezone: "UTC",
      isActive: true
    }
  },
  schemaVersion: 3,
  tasks: {
    check_budget: {
      name: "check_budget",
      description: "Query current token usage against budget",
      action: "dynatrace.automations:execute-dql-query",
      input: {
        query: `fetch spans, from: now()-24h, to: now()
| filter isNotNull(gen_ai.provider.name) OR isNotNull(gen_ai.request.model)
| summarize {
    total_tokens = sum(coalesce(gen_ai.usage.prompt_tokens, gen_ai.usage.input_tokens, 0) + coalesce(gen_ai.usage.completion_tokens, gen_ai.usage.output_tokens, 0))
  }
| fields total_tokens, budget_limit = 1000000, usage_percent = (total_tokens / 1000000) * 100`
      },
      position: { x: 0, y: 1 }
    },
    evaluate_threshold: {
      name: "evaluate_threshold",
      description: "Check if usage exceeds 80% of budget",
      action: "dynatrace.automations:run-javascript",
      input: {
        script: `
const result = {{ result("check_budget") }};
const usagePercent = result[0]?.usage_percent || 0;
const shouldAlert = usagePercent >= 80;
return { 
  shouldAlert, 
  usagePercent: usagePercent.toFixed(1),
  totalTokens: result[0]?.total_tokens || 0
};`
      },
      position: { x: 0, y: 2 },
      predecessors: ["check_budget"]
    },
    send_slack_alert: {
      name: "send_slack_alert",
      description: "Send Slack alert if threshold exceeded",
      action: "dynatrace.automations:send-slack-message",
      input: {
        channel: "{{$.trigger.slackChannel}}",
        message: `⚠️ *GenAI Token Budget Alert*

Usage has reached *{{ result("evaluate_threshold").usagePercent }}%* of daily budget.

• Total Tokens: {{ result("evaluate_threshold").totalTokens | number }}
• Budget Limit: 1,000,000 tokens

Consider throttling non-critical workloads or reviewing high-volume consumers.

_Sent by GenAI Control Center_`
      },
      position: { x: 0, y: 3 },
      predecessors: ["evaluate_threshold"],
      conditions: {
        custom: "{{ result('evaluate_threshold').shouldAlert == true }}"
      }
    }
  },
  ownerType: "USER",
  isPrivate: false
};

/**
 * Model Error Rate Monitor Workflow
 * - Monitors error rates by model
 * - Triggers ServiceNow incident on spike
 */
export const ERROR_RATE_MONITOR_WORKFLOW = {
  title: "GCC: Model Error Rate Monitor",
  description: "Monitor GenAI model error rates and create incidents on spikes",
  trigger: {
    davisProblem: {
      categories: ["ERROR"],
      entityTags: {
        contains: ["genai:true"]
      }
    }
  },
  schemaVersion: 3,
  tasks: {
    get_problem_context: {
      name: "get_problem_context",
      description: "Extract problem details",
      action: "dynatrace.automations:run-javascript",
      input: {
        script: `
const problem = {{ $.event }};
return {
  problemId: problem.display_id,
  title: problem.title,
  severity: problem.severity,
  affectedEntity: problem.affected_entity_ids?.[0] || 'Unknown',
  startTime: problem.start_time
};`
      },
      position: { x: 0, y: 1 }
    },
    analyze_error_pattern: {
      name: "analyze_error_pattern",
      description: "Use Davis Intelligence to analyze error pattern",
      action: "dynatrace.automations:dynatrace-intelligence",
      input: {
        prompt: `A Davis problem was detected for a GenAI service:

Problem: {{ result("get_problem_context").title }}
Severity: {{ result("get_problem_context").severity }}
Affected Entity: {{ result("get_problem_context").affectedEntity }}

Analyze this problem and provide:
1. Likely root cause (rate limiting, API errors, model unavailability)
2. Recommended immediate action
3. Whether this requires human intervention (yes/no)`
      },
      position: { x: 0, y: 2 },
      predecessors: ["get_problem_context"]
    },
    create_incident: {
      name: "create_incident",
      description: "Create ServiceNow incident",
      action: "dynatrace.automations:servicenow-create-incident",
      input: {
        shortDescription: "GenAI Model Error: {{ result('get_problem_context').title }}",
        description: `{{ result("analyze_error_pattern") }}`,
        urgency: "2",
        impact: "2",
        category: "AI/ML Services"
      },
      position: { x: 0, y: 3 },
      predecessors: ["analyze_error_pattern"]
    }
  },
  ownerType: "USER",
  isPrivate: false
};

// Workflow deployment helper (requires @dynatrace-sdk/client-automation)
export async function deployWorkflow(workflow: typeof FINOPS_DIGEST_WORKFLOW): Promise<string> {
  // Placeholder - implement when automation SDK is added
  console.log('[GCC] Workflow deployment requires @dynatrace-sdk/client-automation');
  console.log('[GCC] Use getWorkflowDeployUrl() for manual import instead');
  return 'manual-deploy-required';
}

// Get workflow deployment URL for manual import
export function getWorkflowDeployUrl(workflowJson: object): string {
  const encoded = encodeURIComponent(JSON.stringify(workflowJson));
  return `https://demo.apps.dynatrace.com/ui/apps/dynatrace.workflows/builder?import=${encoded}`;
}
